defaults:
  - encoder: hf_bert
  - datasets: retriever_default # contains a list of all possible sources of queries for evaluation. Specific set is selected by qa_dataset parameter
  - ctx_sources: default_sources

indexers:
  flat:
    _target_: dpr.indexer.faiss_indexers.DenseFlatIndexer

  hnsw:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWFlatIndexer

  hnsw_sq:
    _target_: dpr.indexer.faiss_indexers.DenseHNSWSQIndexer

indexer: flat

# A trained bi-encoder checkpoint file to initialize the model
model_file:

# Name of the all-passages resource
ctx_src:

# the name of the queries dataset from the 'datasets' config group
qa_dataset:

# output .json file path to write results to
out_file:
# "regex" or "string"
match: string
n_docs: 100
validation_workers: 16

# Whether to lower case the input text. Set True for uncased models, False for the cased ones.
do_lower_case: True

# Batch size for the embedding generation
batch_size: 256

# tokens which won't be slit by tokenizer
special_tokens:


# TODO: move to a conf group
# local_rank for distributed training on gpus
local_rank: -1
device:
distributed_world_size:
distributed_port:
no_cuda: False
n_gpu:
fp16: False

# For fp16: Apex AMP optimization level selected in ['O0', 'O1', 'O2', and 'O3']."
#        "See details at https://nvidia.github.io/apex/amp.html
fp16_opt_level: O1
